version: '3'

services:

  db:
      image: mariadb:latest
      environment:
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'admin'
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: dashboard
      ports:
        - "3306:3306"
      networks:
        web-bridge:
          aliases:
            - mysql.local

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      web-bridge:

  apache:
      image: httpd:latest
      ports:
        - 80:80
      volumes:
        - ./frontend:/usr/local/apache2/htdocs

networks:
  web-bridge: